ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.sgonly.online
CATALOGUE_HOST: catalogue-dev.sgonly.online
REDIS_HOST: redis-dev.sgonly.online
USER_HOST: user-dev.sgonly.online
CART_HOST: cart-dev.sgonly.online
MYSQL_HOST: mysql-dev.sgonly.online
SHIPPING_HOST: shipping-dev.sgonly.online
RABBITMQ_HOST: rabbitmq-dev.sgonly.online
PAYMENT_HOST: payment-dev.sgonly.online